// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT-KZJnGVtdW4cadFSfglXFUsiJfzYdO0',
    appId: '1:623868404552:web:ac7a5c8e02f240698dc97d',
    messagingSenderId: '623868404552',
    projectId: 'flutter-tutorial-a49fb',
    authDomain: 'flutter-tutorial-a49fb.firebaseapp.com',
    storageBucket: 'flutter-tutorial-a49fb.appspot.com',
    measurementId: 'G-M5HH134724',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPWDZP-K4E9OBy0NVuHhFWI7XDY0_qA8o',
    appId: '1:623868404552:android:9f052ac213bc43898dc97d',
    messagingSenderId: '623868404552',
    projectId: 'flutter-tutorial-a49fb',
    storageBucket: 'flutter-tutorial-a49fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWUDZ7Iu86X_GIse3ZaBaCYoJZd85abrE',
    appId: '1:623868404552:ios:4985220e1ab9b66d8dc97d',
    messagingSenderId: '623868404552',
    projectId: 'flutter-tutorial-a49fb',
    storageBucket: 'flutter-tutorial-a49fb.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWUDZ7Iu86X_GIse3ZaBaCYoJZd85abrE',
    appId: '1:623868404552:ios:dcb4b35cc11d08e48dc97d',
    messagingSenderId: '623868404552',
    projectId: 'flutter-tutorial-a49fb',
    storageBucket: 'flutter-tutorial-a49fb.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
